
const STUDENTS=['ABDURROHMAN NAAJID', 'ABHIENAYA NAGATHA', 'ADLHI DHENASTA ADILAN PRATAMA', 'AHMAD KURNIA RAJANI', 'AL FATAH', 'AZKA ALDRIC PUTRA', 'BILAL ADZUNNU MALDINI', 'BINTANG IBNU YUSAMI', 'CARLYSYAH PUTRI HERI ANA INDRAYATI', 'CIKAL RABBANI', 'GALANG PUTRA PRATAMA', 'GILANG TRI PRAYOGA', 'GUSTI TARUNA AFKAR', 'HESTI ZASKIA AGUSTIN', 'IFAT ACHMAD KHAIRY', 'IFTINA ASSYABIYA RAFIFA', 'JELITA RAUDHA ADELIA SYUHADA', 'KHURUNNISA ADELIA', 'MEVIAWAN LISTANTO', 'MILAN ZAHRANA EMILIAN SIBURIAN', 'MUHAMMAD DARIUS ABIDIN', 'MUHAMMADGIBRAN ARTANABIL', 'MUTIA ELIZA', 'NADIAH OKTAVIA', 'NAUFAL YUSUF HARYAWAN', 'OKKY AULIA PUTRI', 'RADITYA PRATAMA', 'SHERIL ADEL SHEINAFIA'];
const SUBJECTS=["Pendidikan Pancasila","Bahasa Indonesia","Bahasa Inggris","Koding & Kecerdasan Artifisial","Matematika","PJOK","Pramuka","IPAS","PAI","PLBJ","Seni Rupa"];
const KEY="detektif_cilik_absensi_6b_v1";
function getData(){return JSON.parse(localStorage.getItem(KEY)||"[]")}
function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function fillSelect(id,items,placeholder){const el=document.getElementById(id);if(!el)return;el.innerHTML=placeholder?`<option value="">${placeholder}</option>`:"";items.forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;el.appendChild(o)})}
function initCommon(){fillSelect("student",STUDENTS,"Pilih nama siswa");fillSelect("subject",SUBJECTS,"Pilih mata pelajaran")}
function previewPhoto(){const f=document.getElementById("photo"),p=document.getElementById("preview"),img=document.getElementById("previewImg");if(f.files[0]){img.src=URL.createObjectURL(f.files[0]);p.style.display="block"}}
function submitAttendance(){const name=document.getElementById("student").value,subject=document.getElementById("subject").value,status=document.getElementById("statusSelect").value,note=document.getElementById("note").value,photo=document.getElementById("photo").files[0];if(!name||!subject||!status){alert("Lengkapi nama, mata pelajaran, dan status.");return}const rec={id:Date.now(),time:new Date().toISOString(),name,subject,status,note,photoName:photo?photo.name:"",photoData:""};if(photo){const reader=new FileReader();reader.onload=()=>{rec.photoData=reader.result;finish(rec)};reader.readAsDataURL(photo)}else finish(rec)}
function finish(rec){const d=getData();d.push(rec);saveData(d);const s=document.getElementById("success");s.className="status show";s.innerHTML=`🕵️ <b>MISI BERHASIL!</b><br>Kehadiran ${rec.name} tercatat pada ${new Date(rec.time).toLocaleString("id-ID")}.`;document.getElementById("photo").value="";document.getElementById("preview").style.display="none";}
function renderDashboard(){const d=getData();const date=document.getElementById("dateFilter").value;const subject=document.getElementById("subjectFilter").value;const rows=d.filter(x=>(!date||x.time.slice(0,10)===date)&&(!subject||x.subject===subject)).sort((a,b)=>b.time.localeCompare(a.time));document.getElementById("all").textContent=rows.length;document.getElementById("hadir").textContent=rows.filter(x=>x.status==="Hadir").length;document.getElementById("izin").textContent=rows.filter(x=>x.status==="Izin").length;document.getElementById("sakit").textContent=rows.filter(x=>x.status==="Sakit").length;document.getElementById("tbody").innerHTML=rows.map(x=>`<tr><td>${new Date(x.time).toLocaleString("id-ID")}</td><td>${x.name}</td><td>${x.subject}</td><td>${x.status}</td><td>${x.photoData?`<a href="${x.photoData}" target="_blank"><img class="photo" src="${x.photoData}"></a>`:"—"}</td><td>${x.note||"—"}</td></tr>`).join("")||"<tr><td colspan='6'>Belum ada data.</td></tr>"}
function exportCSV(){const rows=[...document.querySelectorAll("#tbody tr")].map(tr=>[...tr.children].slice(0,4).map(td=>td.innerText));let csv="Waktu,Nama,Mapel,Status\n"+rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="rekap_absensi_6B.csv";a.click()}
function clearAll(){if(confirm("Hapus semua data absensi di perangkat ini?")){localStorage.removeItem(KEY);renderDashboard()}}
function initGuru(){fillSelect("subjectFilter",SUBJECTS,"Semua mata pelajaran");document.getElementById("dateFilter").value=new Date().toISOString().slice(0,10);renderDashboard()}
